### ISSUE TITLE
Thread Unsafe Code

### ISSUE THREAD

**Issue by thygrrr** [LunaMultiplayer/CachedQuickLz#2]
https://github.com/LunaMultiplayer/CachedQuickLz/blob/1ef0fab5c7269355fb62a74e9402f4e10fe4b48b/CachedQuickLz/ArrayPool.cs#L29

The problem with this code is that the Stack that it Pops is not thread safe. So between the methods/getters on the ConcurrentSet Bins, there can be something that happens; especially during Stack.Pop or the ternary operator in the assignment (they are also nonatomic), that would result in undefined behaviour, for instance the same element getting popped twice.

However, this issue is somewhat unlikely to be causing  https://github.com/LunaMultiplayer/LunaMultiplayer/issues/195, because WriteHeader has no easily conceivable way of writing the bits as 10, only 11 or 01. However, it could happen that the data is entirely garbled because multiple writes to the same variable could be cached; and byte writes are seldom atomic.

**Comment by thygrrr** [comment]
At worst, this can result in a crash when the bin is popped twice.

**Comment by thygrrr** [comment]
I'd suggest using:
- ConcurrentStack
- **AND** use the TryPop method instead of the `bin.Count > 0 ? ...` because that is not thread safe.

**Comment by gavazquez** [comment]
Totally agree

**Comment by gavazquez** [comment]
ok fixed
